fix

diff --git a/.github/workflows/custom_image_build.yaml b/.github/workflows/custom_image_build.yaml
--- a/.github/workflows/custom_image_build.yaml
+++ b/.github/workflows/custom_image_build.yaml
@@ -24,7 +24,11 @@ jobs:
           -H "Authorization: Bearer ${{ secrets.CONTENTS_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/mu-ruU1/docker-kubernetes-tutorial/releases/tags/v1)
-        url=$(echo $json_data | jq -r '.url')
+        if [ $? -ne 0 ]; then
+          echo "Failed to get JSON data from API"
+          exit 1
+        fi
+        url=$(echo "$json_data" | jq -r '.url')
 
     - name: Delete Release
       run: |
@@ -33,7 +37,7 @@ jobs:
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.CONTENTS_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          $url
+          "$url"
 
   build_and_release:
     needs: delete_release
