整形

diff --git a/.github/workflows/custom_image_build.yaml b/.github/workflows/custom_image_build.yaml
--- a/.github/workflows/custom_image_build.yaml
+++ b/.github/workflows/custom_image_build.yaml
@@ -10,34 +10,34 @@ env:
   IMAGE_FILE: ubuntu-custom-cloudimg.img
 
 jobs:
-# https://docs.github.com/ja/rest/releases/releases?apiVersion=2022-11-28#delete-a-release
-# https://docs.github.com/ja/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-contents
+  # https://docs.github.com/ja/rest/releases/releases?apiVersion=2022-11-28#delete-a-release
+  # https://docs.github.com/ja/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-contents
 
   delete_release:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Get Release ID and Delete Release
-      run: |
-        json_data=$(curl -L \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.CONTENTS_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/mu-ruU1/docker-kubernetes-tutorial/releases/tags/v1)
+      - name: Get Release ID and Delete Release
+        run: |
+          json_data=$(curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.CONTENTS_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/mu-ruU1/docker-kubernetes-tutorial/releases/tags/v1)
 
-        if [ $? -ne 0 ]; then
-          echo "Failed to get JSON data from API"
-          exit 1
-        fi
+          if [ $? -ne 0 ]; then
+            echo "Failed to get JSON data from API"
+            exit 1
+          fi
 
-        url=$(echo "$json_data" | jq -r '.url')
+          url=$(echo "$json_data" | jq -r '.url')
 
-        curl -L \
-          -X DELETE \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.CONTENTS_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          "$url"
+          curl -L \
+            -X DELETE \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.CONTENTS_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "$url"
 
   build_and_release:
     needs: delete_release
@@ -80,7 +80,7 @@ jobs:
             |Filename|sha256 hash|
             |:--:|:--:|
             |[ubuntu-custom-cloudimg.img](https://github.com/mu-ruU1/docker-kubernetes-tutorial/releases/download/v1/ubuntu-custom-cloudimg.img)|${{ env.HASH }}|
-  
+
             - Downloaded from ${{ env.URL_TO_OS_IMAGE }}
             - Customized by virt-customize
               - Installed qemu-guest-agent
